#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION=watch
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  run)
    cd "$THIS_DIR"
    mkdir -p tmp/in tmp/out
    sh_color ORANGE "=== {{Compiling}}..."
    my_crystal __ build specs/specs.cr -o tmp/out/specs
    sh_color ORANGE "=== {{Running}}..."
    tmp/out/specs
    ;;

  watch)
    local +x CMD="shell_out specs run"
    ${=CMD} || :
    process watch "-r sh -r bin -r specs -r src" "$CMD"
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

